/**
 * BugFlow Shared Package - Barrel Export
 * Re-exports all types, schemas, and constants from a single entry point.
 */

export type {
  ISODateString,
  Platform,
  TeamRole,
  Team,
  TeamMember,
  InviteStatus,
  TeamInvite,
  Integration,
  ClassificationStatus,
  IncomingMessage,
  BugStatus,
  BugSeverity,
  BugCategory,
  BugReport,
  MondayBacklogItem,
  JobType,
  JobStatus,
  Job,
  AlertType,
  TrendAlert,
  DigestBugBreakdown,
  WeeklyDigest,
  TeamSettings,
} from './types';

export {
  isoDateStringSchema,
  platformSchema,
  teamRoleSchema,
  teamSchema,
  teamMemberSchema,
  inviteStatusSchema,
  teamInviteSchema,
  integrationSchema,
  classificationStatusSchema,
  incomingMessageSchema,
  bugStatusSchema,
  bugSeveritySchema,
  bugCategorySchema,
  bugReportSchema,
  mondayBacklogItemSchema,
  jobTypeSchema,
  jobStatusSchema,
  jobSchema,
  alertTypeSchema,
  trendAlertSchema,
  digestBugBreakdownSchema,
  weeklyDigestSchema,
  teamSettingsSchema,
  slackWebhookPayloadSchema,
  discordWebhookPayloadSchema,
  intercomWebhookPayloadSchema,
  telegramWebhookPayloadSchema,
  mondayWebhookPayloadSchema,
  xWebhookPayloadSchema,
  webhookPayloadSchema,
  classificationResultSchema,
  bugExtractionResultSchema,
  dedupResultSchema,
} from './schemas';

export type {
  PlatformSchema,
  TeamSchema,
  TeamMemberSchema,
  TeamInviteSchema,
  IntegrationSchema,
  IncomingMessageSchema,
  BugReportSchema,
  MondayBacklogItemSchema,
  JobSchema,
  TrendAlertSchema,
  DigestBugBreakdownSchema,
  WeeklyDigestSchema,
  TeamSettingsSchema,
  SlackWebhookPayload,
  DiscordWebhookPayload,
  IntercomWebhookPayload,
  TelegramWebhookPayload,
  MondayWebhookPayload,
  XWebhookPayload,
  WebhookPayload,
  ClassificationResult,
  BugExtractionResult,
  DedupResult,
} from './schemas';

export {
  PLATFORMS,
  SEVERITIES,
  BUG_STATUSES,
  JOB_TYPES,
  CLASSIFICATION_STATUSES,
  DEFAULT_SETTINGS,
} from './constants';
