import type { BugReport, IncomingMessage, TrendAlert } from '@/lib/hooks/use-realtime';

const DEV_TEAM_ID = '00000000-0000-0000-0000-000000000000';

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

function daysAgo(d: number): string {
  return new Date(Date.now() - d * 24 * 60 * 60 * 1000).toISOString();
}

// ── Incoming Messages ──────────────────────────────────────────────────────

export const MOCK_MESSAGES: IncomingMessage[] = [
  {
    id: 'msg-001',
    team_id: DEV_TEAM_ID,
    channel_type: 'slack',
    channel_id: '#bug-reports',
    sender_name: 'Sarah Chen',
    content: 'The checkout page is completely broken on mobile. When I tap "Pay Now" nothing happens, the button just flashes and the page freezes.',
    bug_report_id: 'bug-001',
    processed: true,
    created_at: hoursAgo(0.5),
  },
  {
    id: 'msg-002',
    team_id: DEV_TEAM_ID,
    channel_type: 'discord',
    channel_id: '#support',
    sender_name: 'Alex Rivera',
    content: 'Hey, I keep getting a 500 error when trying to upload images larger than 5MB. The error message just says "Something went wrong" which isn\'t helpful at all.',
    bug_report_id: 'bug-002',
    processed: true,
    created_at: hoursAgo(1),
  },
  {
    id: 'msg-003',
    team_id: DEV_TEAM_ID,
    channel_type: 'intercom',
    channel_id: 'conv-4821',
    sender_name: 'Jordan Martinez',
    content: 'I\'m on the enterprise plan and the SSO login has been failing intermittently since the last update. About 30% of our team can\'t log in on any given attempt.',
    bug_report_id: 'bug-003',
    processed: true,
    created_at: hoursAgo(2),
  },
  {
    id: 'msg-004',
    team_id: DEV_TEAM_ID,
    channel_type: 'telegram',
    channel_id: 'support-group',
    sender_name: 'Priya Patel',
    content: 'Dashboard charts are showing data from the wrong timezone. All my analytics are off by 8 hours which makes the daily reports useless.',
    bug_report_id: 'bug-004',
    processed: true,
    created_at: hoursAgo(3),
  },
  {
    id: 'msg-005',
    team_id: DEV_TEAM_ID,
    channel_type: 'slack',
    channel_id: '#engineering',
    sender_name: 'Marcus Johnson',
    content: 'The search function is extremely slow, taking 15+ seconds to return results. It used to be instant. Something changed with the last deploy.',
    bug_report_id: 'bug-005',
    processed: true,
    created_at: hoursAgo(4),
  },
  {
    id: 'msg-006',
    team_id: DEV_TEAM_ID,
    channel_type: 'discord',
    channel_id: '#bugs',
    sender_name: 'Emily Watson',
    content: 'When I export a CSV report, the date columns are formatted incorrectly. They show as Unix timestamps instead of readable dates.',
    bug_report_id: 'bug-006',
    processed: true,
    created_at: hoursAgo(5),
  },
  {
    id: 'msg-007',
    team_id: DEV_TEAM_ID,
    channel_type: 'intercom',
    channel_id: 'conv-4835',
    sender_name: 'David Kim',
    content: 'The notification preferences page doesn\'t save changes. I toggle email notifications off, click save, but when I refresh the page it\'s back to on.',
    bug_report_id: 'bug-007',
    processed: true,
    created_at: hoursAgo(6),
  },
  {
    id: 'msg-008',
    team_id: DEV_TEAM_ID,
    channel_type: 'slack',
    channel_id: '#bug-reports',
    sender_name: 'Lisa Thompson',
    content: 'Mobile checkout is still broken for me too! Same issue Sarah reported. Using iPhone 15 Pro with Safari.',
    bug_report_id: 'bug-001',
    processed: true,
    created_at: hoursAgo(0.3),
  },
  {
    id: 'msg-009',
    team_id: DEV_TEAM_ID,
    channel_type: 'telegram',
    channel_id: 'support-group',
    sender_name: 'Omar Hassan',
    content: 'Getting rate limited on the API even though I\'m well under my quota. Started happening after the v2.4 update.',
    bug_report_id: null,
    processed: false,
    created_at: hoursAgo(0.1),
  },
  {
    id: 'msg-010',
    team_id: DEV_TEAM_ID,
    channel_type: 'discord',
    channel_id: '#support',
    sender_name: 'Nina Kowalski',
    content: 'The dark mode toggle doesn\'t persist between sessions. Every time I open the app it resets to light mode.',
    bug_report_id: null,
    processed: false,
    created_at: hoursAgo(0.05),
  },
];

// ── Bug Reports ────────────────────────────────────────────────────────────

export const MOCK_BUGS: BugReport[] = [
  {
    id: 'bug-001',
    team_id: DEV_TEAM_ID,
    title: 'Checkout button unresponsive on mobile Safari',
    description: 'The "Pay Now" button on the checkout page does not trigger the payment flow on mobile Safari. The button flashes on tap but no action is taken. The page becomes unresponsive after the tap.',
    steps_to_reproduce: '1. Navigate to /checkout on a mobile device (iOS Safari)\n2. Fill in payment details\n3. Tap "Pay Now" button\n4. Observe: button flashes but nothing happens\n5. Page becomes unresponsive to further taps',
    severity: 'critical',
    category: 'ui',
    status: 'pending_review',
    review_status: 'pending',
    confidence_score: 0.96,
    source_channel: 'slack',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 3,
    source_message_ids: ['msg-001', 'msg-008'],
    created_at: hoursAgo(0.5),
    updated_at: hoursAgo(0.3),
  },
  {
    id: 'bug-002',
    team_id: DEV_TEAM_ID,
    title: '500 error on image uploads exceeding 5MB',
    description: 'Users receive a generic "Something went wrong" error when attempting to upload images larger than 5MB. The server returns a 500 status code. The error occurs in both the web and API upload endpoints.',
    steps_to_reproduce: '1. Navigate to any image upload area\n2. Select an image file larger than 5MB\n3. Click upload\n4. Observe: 500 error with message "Something went wrong"',
    severity: 'high',
    category: 'api',
    status: 'pending_review',
    review_status: 'pending',
    confidence_score: 0.92,
    source_channel: 'discord',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: ['msg-002'],
    created_at: hoursAgo(1),
    updated_at: hoursAgo(1),
  },
  {
    id: 'bug-003',
    team_id: DEV_TEAM_ID,
    title: 'SSO login failing intermittently for enterprise users',
    description: 'Enterprise SSO authentication fails approximately 30% of the time since the v2.3 update. Users receive a "Authentication failed" error and must retry. This affects SAML-based SSO providers.',
    steps_to_reproduce: '1. Navigate to /login\n2. Click "Sign in with SSO"\n3. Enter enterprise domain\n4. Complete SSO flow with identity provider\n5. Observe: ~30% chance of "Authentication failed" error',
    severity: 'critical',
    category: 'auth',
    status: 'pending_review',
    review_status: 'pending',
    confidence_score: 0.94,
    source_channel: 'intercom',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: ['msg-003'],
    created_at: hoursAgo(2),
    updated_at: hoursAgo(2),
  },
  {
    id: 'bug-004',
    team_id: DEV_TEAM_ID,
    title: 'Dashboard analytics showing wrong timezone offset',
    description: 'All dashboard charts and analytics display data with an 8-hour timezone offset. Daily reports show activity at incorrect times, making usage analytics unreliable.',
    steps_to_reproduce: '1. Open the analytics dashboard\n2. View any daily chart\n3. Compare data points with known activity times\n4. Observe: all data points are shifted by +8 hours',
    severity: 'medium',
    category: 'data',
    status: 'approved',
    review_status: 'approved',
    confidence_score: 0.88,
    source_channel: 'telegram',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: 'MON-1234',
    report_count: 1,
    source_message_ids: ['msg-004'],
    created_at: hoursAgo(3),
    updated_at: hoursAgo(1.5),
  },
  {
    id: 'bug-005',
    team_id: DEV_TEAM_ID,
    title: 'Search performance degradation - 15s+ response times',
    description: 'The search functionality has degraded significantly since the last deploy. Queries that previously returned in under 1 second now take 15+ seconds. This appears to affect all search endpoints.',
    steps_to_reproduce: '1. Navigate to any page with search functionality\n2. Enter a search query\n3. Observe: results take 15+ seconds to appear\n4. Previously this was near-instant',
    severity: 'high',
    category: 'performance',
    status: 'approved',
    review_status: 'approved',
    confidence_score: 0.91,
    source_channel: 'slack',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: 'MON-1235',
    report_count: 2,
    source_message_ids: ['msg-005'],
    created_at: hoursAgo(4),
    updated_at: hoursAgo(2),
  },
  {
    id: 'bug-006',
    team_id: DEV_TEAM_ID,
    title: 'CSV export shows Unix timestamps instead of formatted dates',
    description: 'When exporting reports to CSV, date columns display raw Unix timestamps (e.g., 1708300800) instead of human-readable date formats (e.g., 2024-02-19).',
    steps_to_reproduce: '1. Navigate to Reports\n2. Click "Export CSV"\n3. Open the downloaded file\n4. Check date columns\n5. Observe: dates are Unix timestamps',
    severity: 'low',
    category: 'data',
    status: 'created_in_monday',
    review_status: 'approved',
    confidence_score: 0.85,
    source_channel: 'discord',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: 'MON-1230',
    report_count: 1,
    source_message_ids: ['msg-006'],
    created_at: hoursAgo(5),
    updated_at: hoursAgo(3),
  },
  {
    id: 'bug-007',
    team_id: DEV_TEAM_ID,
    title: 'Notification preferences not persisting after save',
    description: 'Changes to notification preferences (email, push, in-app) revert to defaults after page refresh. The save action appears to succeed (shows success toast) but changes are not actually persisted.',
    steps_to_reproduce: '1. Go to Settings → Notifications\n2. Toggle any preference off\n3. Click Save\n4. Observe: success message appears\n5. Refresh the page\n6. Observe: preference is back to its previous state',
    severity: 'medium',
    category: 'ui',
    status: 'pending_review',
    review_status: 'pending',
    confidence_score: 0.87,
    source_channel: 'intercom',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: ['msg-007'],
    created_at: hoursAgo(6),
    updated_at: hoursAgo(6),
  },
  {
    id: 'bug-008',
    team_id: DEV_TEAM_ID,
    title: 'Duplicate: Mobile checkout failure (same as BUG-001)',
    description: 'Additional report of checkout button not working on mobile. Same root cause as BUG-001.',
    steps_to_reproduce: null,
    severity: 'critical',
    category: 'ui',
    status: 'merged',
    review_status: 'merged',
    confidence_score: 0.93,
    source_channel: 'slack',
    dedup_match_id: 'bug-001',
    consolidated_summary: 'Multiple users reporting checkout button failure on mobile Safari. The button visually responds to taps but does not trigger the payment flow. Confirmed on iPhone 15 Pro and iPhone 14. Likely a Safari-specific JavaScript event handling issue.',
    monday_item_id: null,
    report_count: 1,
    source_message_ids: ['msg-008'],
    created_at: hoursAgo(0.3),
    updated_at: hoursAgo(0.2),
  },
  {
    id: 'bug-009',
    team_id: DEV_TEAM_ID,
    title: 'Team invite emails not being delivered',
    description: 'Team invite emails are not being received by invitees. The invite appears to be created in the system but no email is delivered. Affects all email providers.',
    steps_to_reproduce: '1. Go to Settings → Team\n2. Click "Invite Member"\n3. Enter an email address\n4. Click Send Invite\n5. Observe: invite shows as sent in UI\n6. Observe: invitee never receives the email',
    severity: 'high',
    category: 'api',
    status: 'approved',
    review_status: 'approved',
    confidence_score: 0.89,
    source_channel: 'slack',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: [],
    created_at: daysAgo(1),
    updated_at: daysAgo(0.5),
  },
  {
    id: 'bug-010',
    team_id: DEV_TEAM_ID,
    title: 'Keyboard shortcut conflicts with browser defaults',
    description: 'Custom keyboard shortcuts (Ctrl+K for search, Ctrl+/ for help) conflict with browser default shortcuts, causing unexpected behavior.',
    steps_to_reproduce: '1. Press Ctrl+K in the app\n2. Observe: both app search and browser address bar activate simultaneously',
    severity: 'low',
    category: 'ui',
    status: 'rejected',
    review_status: 'rejected',
    confidence_score: 0.62,
    source_channel: 'discord',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: [],
    created_at: daysAgo(2),
    updated_at: daysAgo(1.5),
  },
  {
    id: 'bug-011',
    team_id: DEV_TEAM_ID,
    title: 'Webhook delivery failing silently for Slack integration',
    description: 'Slack webhook deliveries are failing without any error logging. Messages sent from monitored channels are not being captured by the system.',
    steps_to_reproduce: '1. Send a message in a monitored Slack channel\n2. Check BugFlow incoming messages\n3. Observe: message does not appear',
    severity: 'high',
    category: 'api',
    status: 'pending_review',
    review_status: 'pending',
    confidence_score: 0.90,
    source_channel: 'slack',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: null,
    report_count: 1,
    source_message_ids: [],
    created_at: hoursAgo(1.5),
    updated_at: hoursAgo(1.5),
  },
  {
    id: 'bug-012',
    team_id: DEV_TEAM_ID,
    title: 'Memory leak in real-time subscription handler',
    description: 'The WebSocket subscription for real-time updates leaks memory over time. After ~2 hours of keeping the dashboard open, browser memory usage grows from 200MB to 1.2GB.',
    steps_to_reproduce: '1. Open the dashboard\n2. Leave it open for 2+ hours\n3. Monitor browser memory usage\n4. Observe: steady memory growth',
    severity: 'medium',
    category: 'performance',
    status: 'approved',
    review_status: 'approved',
    confidence_score: 0.86,
    source_channel: 'discord',
    dedup_match_id: null,
    consolidated_summary: null,
    monday_item_id: 'MON-1236',
    report_count: 1,
    source_message_ids: [],
    created_at: daysAgo(1),
    updated_at: daysAgo(0.5),
  },
];

// ── Trend Alerts ───────────────────────────────────────────────────────────

export const MOCK_ALERTS: TrendAlert[] = [
  {
    id: 'alert-001',
    team_id: DEV_TEAM_ID,
    alert_type: 'spike',
    severity: 'critical',
    message: 'Spike detected: 5 critical/high bugs reported in the last 60 minutes across UI and Auth categories',
    metadata: { bug_count: 5, window_minutes: 60, categories: ['ui', 'auth'] },
    acknowledged: false,
    created_at: hoursAgo(0.5),
  },
  {
    id: 'alert-002',
    team_id: DEV_TEAM_ID,
    alert_type: 'trend',
    severity: 'high',
    message: 'API-related bugs have increased 300% this week compared to the previous week',
    metadata: { category: 'api', increase_pct: 300 },
    acknowledged: false,
    created_at: hoursAgo(4),
  },
];

// ── Integrations ───────────────────────────────────────────────────────────

export const MOCK_INTEGRATIONS = [
  {
    id: 'int-001',
    platform: 'slack' as const,
    enabled: true,
    created_at: daysAgo(14),
    config_summary: 'Monitoring #bug-reports, #engineering',
  },
  {
    id: 'int-002',
    platform: 'discord' as const,
    enabled: true,
    created_at: daysAgo(10),
    config_summary: 'Monitoring #support, #bugs',
  },
  {
    id: 'int-003',
    platform: 'intercom' as const,
    enabled: true,
    created_at: daysAgo(7),
    config_summary: 'All conversation replies',
  },
  {
    id: 'int-004',
    platform: 'telegram' as const,
    enabled: true,
    created_at: daysAgo(5),
    config_summary: 'Support group',
  },
];

// ── Helpers ────────────────────────────────────────────────────────────────

export const MOCK_TEAM_ID = DEV_TEAM_ID;

export function getPendingBugs(): BugReport[] {
  return MOCK_BUGS.filter(b => b.status === 'pending_review');
}

export function getAllBugs(): BugReport[] {
  return MOCK_BUGS;
}

export function getBugById(id: string): BugReport | undefined {
  return MOCK_BUGS.find(b => b.id === id);
}

export function getLinkedMessages(bugId: string): IncomingMessage[] {
  return MOCK_MESSAGES.filter(m => m.bug_report_id === bugId);
}

export function getDuplicateMatch(bug: BugReport): BugReport | null {
  if (!bug.dedup_match_id) return null;
  return MOCK_BUGS.find(b => b.id === bug.dedup_match_id) ?? null;
}
